import p1 from "@/assets/p1.jpg";
import p2 from "@/assets/p2.jpg";
import p3 from "@/assets/p3.jpg";
import p4 from "@/assets/p4.jpg";
import p5 from "@/assets/p5.jpg";
import p6 from "@/assets/p6.jpg";
import p7 from "@/assets/p7.jpg";
import p8 from "@/assets/p8.jpg";
import p9 from "@/assets/p9.jpg";
import p11 from "@/assets/p11.jpg";
import p12 from "@/assets/p12.jpg";
import p13 from "@/assets/p13.jpg";
import p14 from "@/assets/p14.jpg";
import p15 from "@/assets/p15.jpg";
import p16 from "@/assets/p16.jpg";
import p17 from "@/assets/p17.jpg";
import p18 from "@/assets/p18.jpg";
import p19 from "@/assets/p19.jpg";
import p20 from "@/assets/p20.jpg";
import p21 from "@/assets/p21.jpg";
import p22 from "@/assets/p22.jpg";
import p23 from "@/assets/p23.jpg";
import p24 from "@/assets/p24.jpg";
import p25 from "@/assets/p25.jpg";
import p26 from "@/assets/p26.jpg";
import p28 from "@/assets/p28.jpg";
import p29 from "@/assets/p29.jpg";
import p30 from "@/assets/p30.jpg";
import p31 from "@/assets/p31.jpg";
import p32 from "@/assets/p32.jpg";
import p33 from "@/assets/p33.jpg";
import p34 from "@/assets/p34.jpg";
import p35 from "@/assets/p35.jpg";
import p37 from "@/assets/p37.jpg";
import p38 from "@/assets/p38.jpg";
import p40 from "@/assets/p40.jpg";
import p41 from "@/assets/p41.jpg";
import p42 from "@/assets/p42.jpg";
import p43 from "@/assets/p43.jpg";
import p44 from "@/assets/p44.jpg";
import p45 from "@/assets/p45.jpg";
import a2 from "@/assets/a2.jpg";
import a3 from "@/assets/a3.jpg";
import n1Asset from "@/assets/n1.jpg.asset.json";
import n2Asset from "@/assets/n2.jpg.asset.json";
import n3Asset from "@/assets/n3.jpg.asset.json";
import n4Asset from "@/assets/n4.jpg.asset.json";
import n5Asset from "@/assets/n5.jpg.asset.json";
import n6Asset from "@/assets/n6.jpg.asset.json";
import s1Asset from "@/assets/s1.jpg.asset.json";
import s2Asset from "@/assets/s2.jpg.asset.json";
import s3Asset from "@/assets/s3.jpg.asset.json";
import s4Asset from "@/assets/s4.jpg.asset.json";
import s5Asset from "@/assets/s5.jpg.asset.json";
import s6Asset from "@/assets/s6.jpg.asset.json";

export type Product = {
  slug: string;
  name: string;
  price: number;
  ageRange: string;
  category: "boys" | "girls" | "kids" | "accessories" | "footwear";
  gender: "Boys" | "Girls" | "Unisex";
  colors: { name: string; hex: string }[];
  sizes: string[];
  image: string;
  isNew?: boolean;
  bestSeller?: boolean;
  soldOut?: boolean;
  fabric: string;
  care: string;
  description: string;
};

const DEF_CARE = "Machine wash cold · Tumble dry low · Do not bleach";

export const PRODUCTS: Product[] = [
  {
    slug: "yellow-daisy-tulle-romper",
    name: "Yellow Daisy Tulle Puff-Sleeve Romper",
    price: 499,
    ageRange: "3–12 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Sunny Yellow", hex: "#F69E1C" }, { name: "Cream", hex: "#FFF8F0" }],
    sizes: ["3-6 Months", "6-9 Months", "9-12 Months"],
    image: p1,
    isNew: true,
    bestSeller: true,
    fabric: "Cotton with tulle overlay",
    care: DEF_CARE,
    description: "A dreamy yellow daisy-print romper with tulle puff sleeves — perfect for sunny days and tiny twirls.",
  },
  {
    slug: "white-floral-strappy-top",
    name: "White Floral Strappy Top",
    price: 649,
    ageRange: "6–9 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Cream", hex: "#FFF8F0" }, { name: "Soft Pink", hex: "#F28FA3" }],
    sizes: ["6-9 Months"],
    image: p2,
    isNew: true,
    fabric: "Lightweight cotton voile",
    care: "Machine wash cold · Hang dry",
    description: "A breezy strappy top with delicate floral embroidery and a sweet front bow.",
  },
  {
    slug: "cream-waffle-lace-romper",
    name: "Cream Waffle Lace Bow Romper",
    price: 649,
    ageRange: "9–12 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Cream", hex: "#FFF8F0" }],
    sizes: ["9-12 Months"],
    image: p3,
    bestSeller: true,
    fabric: "Waffle cotton with lace trim",
    care: "Hand wash cold · Lay flat to dry",
    description: "A heirloom-style waffle romper trimmed with bow-embroidered lace.",
  },
  {
    slug: "brown-corduroy-collar-romper-set",
    name: "Brown Corduroy Lace-Collar Romper Set",
    price: 599,
    ageRange: "3–12 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Cocoa", hex: "#5B3A29" }],
    sizes: ["3-6 Months", "6-9 Months", "9-12 Months"],
    image: p4,
    soldOut: true,
    fabric: "Soft baby corduroy",
    care: "Machine wash cold · Iron low",
    description: "Cozy corduroy bubble romper with a lace collar — comes with a matching bow headband and ribbed tights.",
  },
  {
    slug: "lilac-floral-lace-collar-romper",
    name: "Lilac Floral Lace-Collar Romper",
    price: 550,
    ageRange: "0–9 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Lilac", hex: "#C8A2D8" }, { name: "Cream", hex: "#FFF8F0" }],
    sizes: ["0-3 Months", "6-9 Months"],
    image: p5,
    bestSeller: true,
    fabric: "Cotton muslin",
    care: "Machine wash cold · Tumble dry low",
    description: "Romantic lilac floral romper with an oversized scalloped lace collar.",
  },
  {
    slug: "pink-stripe-collared-romper",
    name: "Pink Stripe Collared Bubble Romper",
    price: 499,
    ageRange: "3–6 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Pink Stripe", hex: "#E8B4A6" }],
    sizes: ["3-6 Months"],
    image: p6,
    isNew: true,
    bestSeller: true,
    fabric: "Cotton with embroidered detail",
    care: DEF_CARE,
    description: "A vintage-inspired striped romper with embroidered diamonds and a lace ruffle collar.",
  },
  {
    slug: "corduroy-joggers",
    name: "Corduroy Joggers",
    price: 699,
    ageRange: "1–4 Years",
    category: "boys",
    gender: "Boys",
    colors: [{ name: "Cocoa", hex: "#5B3A29" }, { name: "Cream", hex: "#FFF8F0" }],
    sizes: ["1-2 Years", "2-3 Years", "3-4 Years"],
    image: p7,
    isNew: true,
    bestSeller: true,
    fabric: "Stretch baby corduroy",
    care: DEF_CARE,
    description: "Soft corduroy joggers with elastic waist and roomy patch pockets — built for playtime.",
  },
  {
    slug: "linen-button-down-shirt",
    name: "Cotton Linen Button-Down Shirt",
    price: 749,
    ageRange: "1–4 Years",
    category: "boys",
    gender: "Boys",
    colors: [{ name: "Cocoa", hex: "#5B3A29" }, { name: "Cream", hex: "#FFF8F0" }],
    sizes: ["1-2 Years", "2-3 Years", "3-4 Years"],
    image: p8,
    isNew: true,
    bestSeller: true,
    fabric: "Cotton linen blend",
    care: "Machine wash cold · Iron low",
    description: "A relaxed cotton-linen button-down with chest pocket — easy to dress up or down.",
  },
  {
    slug: "black-daisy-puff-sleeve-dress",
    name: "Black Daisy Puff-Sleeve Tulle Dress",
    price: 499,
    ageRange: "1–3 Years",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Black", hex: "#1a1a1a" }],
    sizes: ["1-2 Years", "2-3 Years"],
    image: p9,
    soldOut: true,
    fabric: "Cotton with tulle overlay",
    care: DEF_CARE,
    description: "A playful black tulle dress with puff sleeves and a daisy appliqué front.",
  },
  {
    slug: "beige-scallop-bubble-romper",
    name: "Beige Scallop Bubble Romper",
    price: 399,
    ageRange: "0–12 Months",
    category: "girls",
    gender: "Unisex",
    colors: [{ name: "Beige", hex: "#C9B9A6" }],
    sizes: ["0-3 Months", "3-6 Months", "6-9 Months", "9-12 Months"],
    image: p11,
    isNew: true,
    bestSeller: true,
    fabric: "Cotton linen",
    care: DEF_CARE,
    description: "A minimalist sleeveless bubble romper with a scalloped overlay bodice.",
  },
  {
    slug: "pink-rose-collar-dress",
    name: "Pink Rose Peter-Pan Collar Dress",
    price: 499,
    ageRange: "3–9 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Soft Pink", hex: "#F28FA3" }, { name: "Cream", hex: "#FFF8F0" }],
    sizes: ["3-6 Months", "6-9 Months"],
    image: p12,
    isNew: true,
    bestSeller: true,
    fabric: "Cotton voile",
    care: DEF_CARE,
    description: "A delicate rose-print dress with a ruffled lace peter-pan collar.",
  },
  {
    slug: "ivory-collar-top-lace-skirt-set",
    name: "Ivory Collar Top & Lace Skirt Set",
    price: 599,
    ageRange: "3–12 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Ivory", hex: "#FFF8F0" }, { name: "Mauve", hex: "#B49AA0" }],
    sizes: ["3-6 Months", "6-9 Months", "9-12 Months"],
    image: p13,
    soldOut: true,
    fabric: "Cotton with lace overlay",
    care: "Hand wash cold",
    description: "Ivory peter-pan top paired with a mauve bloomer skirt under floral lace — includes a daisy headband.",
  },
  {
    slug: "sage-floral-smocked-romper-set",
    name: "Sage Floral Smocked Romper with Turban",
    price: 399,
    ageRange: "0–24 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Sage", hex: "#9CAF88" }],
    sizes: ["0-3 Months", "3-6 Months", "6-9 Months", "9-12 Months", "12-18 Months", "18-24 Months"],
    image: p14,
    isNew: true,
    bestSeller: true,
    fabric: "Cotton muslin",
    care: DEF_CARE,
    description: "Smocked-bodice floral romper with tie shoulders — paired with a matching knot turban.",
  },
  {
    slug: "ivory-floral-lace-romper",
    name: "Ivory Floral Lace Tiered Romper",
    price: 550,
    ageRange: "3–12 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Ivory", hex: "#FFF8F0" }, { name: "Rose", hex: "#B85C5C" }],
    sizes: ["3-6 Months", "9-12 Months"],
    image: p15,
    isNew: true,
    bestSeller: true,
    fabric: "Cotton with embroidered lace",
    care: DEF_CARE,
    description: "Ivory floral romper finished with a layered embroidered lace hem.",
  },
  {
    slug: "black-embroidered-floral-romper-set",
    name: "Black Embroidered Floral Romper Set",
    price: 599,
    ageRange: "3–9 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Black", hex: "#1a1a1a" }],
    sizes: ["3-6 Months", "6-9 Months"],
    image: p16,
    isNew: true,
    fabric: "Cotton",
    care: "Machine wash cold",
    description: "Puff-sleeve black romper with hand-embroidered flowers — comes with a bow headband and knee socks.",
  },
  {
    slug: "lace-baby-bonnet",
    name: "Lace Baby Bonnet",
    price: 299,
    ageRange: "0–12 Months",
    category: "accessories",
    gender: "Girls",
    colors: [
      { name: "Cream", hex: "#FFF8F0" },
      { name: "White", hex: "#FFFFFF" },
      { name: "Blue", hex: "#A8C8E0" },
    ],
    sizes: ["Free Size"],
    image: p17,
    fabric: "Cotton lace trim",
    care: "Hand wash cold",
    description: "Vintage-style lace baby bonnet with scalloped daisy trim and tie closure.",
  },
  {
    slug: "ivory-embroidered-bow-romper",
    name: "Ivory Embroidered Bow Long-Sleeve Romper",
    price: 599,
    ageRange: "3–9 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Ivory", hex: "#FFF8F0" }],
    sizes: ["3-6 Months", "6-9 Months"],
    image: p18,
    fabric: "Cotton with tulle skirt",
    care: "Machine wash cold",
    description: "Long-sleeve ivory romper with embroidered bows on the bodice and a soft tulle underlay.",
  },
  {
    slug: "baby-footed-sleepsuit-set",
    name: "Baby Footed Sleepsuit (Set of 4)",
    price: 300,
    ageRange: "0–9 Months",
    category: "boys",
    gender: "Unisex",
    colors: [
      { name: "Teddy Check", hex: "#D9C7A6" },
      { name: "Brown Bear", hex: "#7A4A2B" },
      { name: "Grey Car", hex: "#B8BEC4" },
    ],
    sizes: ["Large"],
    fabric: "Soft ribbed cotton",
    care: "Machine wash warm",
    image: p19,
    description: "A four-pack of full-sleeve footed sleepsuits printed with teddies, cars and bears — zip-front for easy changes.",
  },
  {
    slug: "newborn-bodysuit-set",
    name: "Newborn Bodysuit Set",
    price: 300,
    ageRange: "0–6 Months",
    category: "boys",
    gender: "Unisex",
    colors: [
      { name: "Beige Lion", hex: "#C9B188" },
      { name: "Camel", hex: "#B89070" },
      { name: "Sky Sheep", hex: "#A8C8E0" },
    ],
    sizes: ["Medium"],
    image: p20,
    fabric: "100% cotton",
    care: "Machine wash cold",
    description: "Layered newborn essentials in lion, sheep and rainbow prints — soft snap closures throughout.",
  },
  {
    slug: "teddy-bear-sleepsuit-set",
    name: "Teddy Bear Footed Sleepsuit Set",
    price: 300,
    ageRange: "0–9 Months",
    category: "boys",
    gender: "Unisex",
    colors: [
      { name: "Cream", hex: "#FFF8F0" },
      { name: "Buttercup", hex: "#F4E5A1" },
      { name: "Teddy Check", hex: "#D9C7A6" },
    ],
    sizes: ["Small"],
    image: p21,
    fabric: "Ribbed cotton",
    care: "Machine wash cold",
    description: "Snap-front footed sleepsuits in teddy check, palm and dotted prints — pack of three.",
  },
  {
    slug: "bear-dungaree-romper-set",
    name: "Grey Bear Dungaree Romper with Tee & Cap",
    price: 899,
    ageRange: "3–12 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Stone Grey", hex: "#8A8478" }, { name: "Cream", hex: "#FFF8F0" }],
    sizes: ["3-6 Months", "6-9 Months", "9-12 Months"],
    image: p22,
    soldOut: true,
    fabric: "Cotton",
    care: "Machine wash cold",
    description: "Grey corduroy dungaree bubble romper with an embroidered teddy bear patch, paired with a ribbed cream tee and matching corduroy bear cap.",
  },
  {
    slug: "white-eyelet-bow-top-shorts-set",
    name: "White Eyelet Bow Top & Shorts Set",
    price: 799,
    ageRange: "6–18 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "White", hex: "#FFFFFF" }],
    sizes: ["6-9 Months", "12-18 Months"],
    image: p23,
    isNew: true,
    fabric: "Cotton eyelet",
    care: "Machine wash cold",
    description: "Flutter-sleeve eyelet top with a statement bow, paired with matching ruffle shorts — bow headband included.",
  },
  {
    slug: "floral-teddy-onesie-set",
    name: "Floral & Teddy Baby Onesie Set",
    price: 300,
    ageRange: "0–6 Months",
    category: "boys",
    gender: "Unisex",
    colors: [
      { name: "Rose", hex: "#F8C5C5" },
      { name: "Cream Floral", hex: "#FFF0E8" },
      { name: "Teddy Check", hex: "#D9C7A6" },
    ],
    sizes: ["Medium"],
    image: p24,
    fabric: "100% cotton",
    care: "Machine wash cold",
    description: "Four-piece set of side-snap baby onesies in floral and teddy prints — perfect newborn layering.",
  },
  {
    slug: "sage-tiered-cami-dress",
    name: "Sage Tiered Cami Dress",
    price: 670,
    ageRange: "3–24 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Sage", hex: "#A8C2B0" }],
    sizes: ["3-6 Months", "6-9 Months", "9-12 Months", "12-18 Months", "18-24 Months"],
    image: p25,
    fabric: "Striped cotton voile",
    care: "Machine wash cold",
    description: "Airy three-tiered cami dress with metallic stripe and crochet straps.",
  },
  {
    slug: "maroon-corduroy-pinafore",
    name: "Maroon Corduroy Pinafore Dress",
    price: 699,
    ageRange: "3–24 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Maroon", hex: "#7A2F2F" }],
    sizes: ["3-6 Months", "12-18 Months", "18-24 Months"],
    image: p26,
    fabric: "Baby corduroy",
    care: "Machine wash cold",
    description: "Sleeveless corduroy pinafore with button shoulders and tartan-lined back yoke.",
  },
  {
    slug: "eyelet-cami-gingham-shorts-set",
    name: "Eyelet Cami & Gingham Shorts Set",
    price: 799,
    ageRange: "6–36 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Cream", hex: "#FFF8F0" }, { name: "Beige Gingham", hex: "#D9C2A6" }],
    sizes: ["6-9 Months", "12-18 Months", "18-24 Months", "24-36 Months"],
    image: p28,
    fabric: "Cotton eyelet",
    care: "Machine wash cold",
    description: "Three-tier eyelet cami top with a gingham bow strap, paired with paperbag-waist gingham shorts.",
  },
  {
    slug: "pink-heart-sailor-collar-dress",
    name: "Pink Heart Sailor-Collar Dress",
    price: 699,
    ageRange: "3–9 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Bubblegum Pink", hex: "#F8A4C8" }, { name: "Red", hex: "#D63A3A" }],
    sizes: ["3-6 Months", "6-9 Months"],
    image: p29,
    isNew: true,
    fabric: "Cotton muslin",
    care: "Machine wash cold",
    description: "Heart-printed dress with a contrast sailor collar and front bow detail.",
  },
  {
    slug: "pink-strawberry-dress-set",
    name: "Pink Strawberry Bib-Collar Dress",
    price: 699,
    ageRange: "9–12 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Pink Gingham", hex: "#F8C5D0" }],
    sizes: ["9-12 Months"],
    image: p30,
    isNew: true,
    fabric: "Cotton gingham",
    care: "Machine wash cold",
    description: "Strawberry-printed gingham dress with a ruffled white bib collar — bow headband and tights included.",
  },
  {
    slug: "navy-eyelet-puff-sleeve-dress",
    name: "Navy Eyelet Puff-Sleeve Dress",
    price: 650,
    ageRange: "3–6 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Navy", hex: "#1F2F55" }],
    sizes: ["3-6 Months"],
    image: p31,
    fabric: "Cotton eyelet",
    care: "Machine wash cold",
    description: "All-over eyelet puff-sleeve dress in a deep navy — endlessly versatile.",
  },
  {
    slug: "tartan-ruffle-collar-dress",
    name: "Tartan Ruffle-Collar Dress",
    price: 599,
    ageRange: "0–12 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Red Tartan", hex: "#A8262E" }],
    sizes: ["0-3 Months", "3-6 Months", "6-9 Months", "9-12 Months"],
    image: p32,
    isNew: true,
    bestSeller: true,
    fabric: "Cotton flannel",
    care: "Machine wash cold",
    description: "Classic tartan dress with a layered white ruffle collar and red tulle trim — holiday-ready.",
  },
  {
    slug: "embroidered-top-olive-pinafore-set",
    name: "Embroidered Top & Olive Pinafore Set",
    price: 699,
    ageRange: "0–6 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Cream", hex: "#FFF8F0" }, { name: "Olive", hex: "#6B6A3D" }],
    sizes: ["0-3 Months", "3-6 Months"],
    image: p33,
    fabric: "Cotton",
    care: "Machine wash cold",
    description: "Floral-embroidered peter-pan top layered under an olive linen pinafore.",
  },
  {
    slug: "knit-heart-romper-pompom-hat",
    name: "Knit Heart Romper with Pom-Pom Hat",
    price: 599,
    ageRange: "0–12 Months",
    category: "accessories",
    gender: "Unisex",
    colors: [{ name: "Cream", hex: "#FFF8F0" }, { name: "Camel", hex: "#C9A07A" }],
    sizes: ["0-3 Months", "3-6 Months", "6-9 Months", "9-12 Months"],
    image: p34,
    isNew: true,
    fabric: "Soft cable knit",
    care: "Hand wash cold · Lay flat",
    description: "Cozy knit cable romper with an intarsia heart, paired with a matching pom-pom beanie.",
  },
  {
    slug: "bear-bucket-hat",
    name: "Teddy Bear Bucket Hat",
    price: 349,
    ageRange: "6–24 Months",
    category: "accessories",
    gender: "Unisex",
    colors: [{ name: "Black", hex: "#1a1a1a" }, { name: "Cream", hex: "#FFF8F0" }],
    sizes: ["Free Size"],
    image: p35,
    fabric: "Ribbed cotton",
    care: "Hand wash cold",
    description: "Soft ribbed bucket hat finished with a fuzzy teddy bear patch.",
  },
  {
    slug: "ivory-collar-romper-pink-rose-dress",
    name: "Ivory Collar Romper & Pink Rose Dress",
    price: 899,
    ageRange: "6–12 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Ivory", hex: "#FFF8F0" }, { name: "Mauve Pink", hex: "#D8A8B8" }],
    sizes: ["6-9 Months", "9-12 Months"],
    image: p37,
    fabric: "Cotton with crochet rose appliqué",
    care: "Hand wash cold",
    description: "Ivory peter-pan collar bubble romper paired with a rose-appliquéd mauve lace dress.",
  },
  {
    slug: "ribbed-floral-bonnet-romper",
    name: "Ribbed Floral-Bonnet Romper",
    price: 799,
    ageRange: "12 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Cream", hex: "#FFF8F0" }],
    sizes: ["80"],
    image: p38,
    isNew: true,
    fabric: "Ribbed cotton with chiffon skirt",
    care: "Machine wash cold",
    description: "Long-sleeve ribbed romper with chiffon flutter skirt and floral-appliqué bonnet.",
  },
  {
    slug: "ivory-knit-lace-dress",
    name: "Ivory Knit Lace Cardigan Dress",
    price: 499,
    ageRange: "3–12 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Ivory", hex: "#FFF8F0" }],
    sizes: ["3-6 Months", "6-9 Months", "9-12 Months"],
    image: p40,
    fabric: "Open-knit cotton",
    care: "Hand wash cold",
    description: "Pointelle knit cardigan-style dress with a front bow tie and ruffled neckline.",
  },
  {
    slug: "cream-tulle-bow-flutter-dress",
    name: "Cream Tulle Bow Flutter Dress",
    price: 499,
    ageRange: "6–18 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Cream", hex: "#FFF8F0" }],
    sizes: ["6-9 Months", "12-18 Months"],
    image: p41,
    soldOut: true,
    fabric: "Cotton with tulle overlay",
    care: "Hand wash cold",
    description: "Cream flutter-sleeve dress with tulle overlay and a sweet bow accent.",
  },
  {
    slug: "boys-shirt-shorts-set",
    name: "Boys Shirt & Shorts Set",
    price: 499,
    ageRange: "12–14",
    category: "boys",
    gender: "Boys",
    colors: [{ name: "Olive", hex: "#7A6A3F" }, { name: "Sand", hex: "#D9C7A6" }],
    sizes: ["12", "14"],
    image: p42,
    fabric: "Cotton linen",
    care: "Machine wash cold",
    description: "Short-sleeve collared shirt with embroidered chest detail, paired with elastic-waist shorts.",
  },
  {
    slug: "black-floral-frill-romper",
    name: "Black Floral Frill Romper",
    price: 649,
    ageRange: "3–12 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Black Floral", hex: "#1a1a1a" }],
    sizes: ["3-6 Months", "6-9 Months", "9-12 Months"],
    image: p43,
    soldOut: true,
    fabric: "Cotton muslin",
    care: "Machine wash cold",
    description: "Bold black & cream floral romper with rickrack-trimmed bib and tiered skirt.",
  },
  {
    slug: "smile-again-shirt-shorts-set",
    name: "Cream 'Smile Again' Shirt & Shorts Set",
    price: 649,
    ageRange: "1–4 Years",
    category: "boys",
    gender: "Boys",
    colors: [
      { name: "Cream", hex: "#F5E6C8" },
      { name: "Sand", hex: "#D9C7A6" },
    ],
    sizes: ["1-2 Years", "2-3 Years", "3-4 Years"],
    image: p44,
    bestSeller: true,
    fabric: "Cotton linen blend",
    care: "Machine wash cold · Iron low",
    description: "Short-sleeve collared shirt with 'Smile Again' embroidery, paired with elastic-waist shorts — a smart casual set for baby boys.",
  },
  {
    slug: "black-floral-ricrac-bib-romper",
    name: "Black Floral Ricrac-Bib Bubble Romper",
    price: 499,
    ageRange: "3–9 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Black Floral", hex: "#1a1a1a" }],
    sizes: ["3-6 Months", "6-9 Months"],
    image: p45,
    fabric: "Cotton muslin",
    care: "Machine wash cold",
    description: "Flutter-sleeve black & cream floral bubble romper with a scalloped ricrac-trimmed bib collar.",
  },
  {
    slug: "baby-bow-headband",
    name: "Baby Bow Headband",
    price: 70,
    ageRange: "0–24 Months",
    category: "accessories",
    gender: "Girls",
    colors: [{ name: "Soft Pink", hex: "#F28FA3" }],
    sizes: ["Free Size"],
    image: a2,
    isNew: true,
    fabric: "Cotton Blend",
    care: "Hand wash only",
    description: "Soft and stretchy bow headband perfect for everyday styling.",
  },
  {
    slug: "baby-summer-hat",
    name: "Baby Summer Hat",
    price: 249,
    ageRange: "0–3 Years",
    category: "accessories",
    gender: "Unisex",
    colors: [{ name: "Blue", hex: "#207CD8" }],
    sizes: ["Free Size"],
    image: a3,
    bestSeller: true,
    fabric: "Breathable Cotton",
    care: "Machine wash cold",
    description: "Lightweight summer hat that protects little ones from the sun.",
  },
  {
    slug: "cream-3d-floral-lace-tulle-romper",
    name: "Cream 3D Floral Lace Tulle Bubble Romper",
    price: 899,
    ageRange: "6–24 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Cream", hex: "#FFF8F0" }],
    sizes: ["6-12 Months", "12-18 Months", "18-24 Months"],
    image: n1Asset.url,
    isNew: true,
    bestSeller: true,
    fabric: "3D floral lace with tulle overlay",
    care: "Hand wash cold · Lay flat to dry",
    description: "Long-sleeve cream romper in textured 3D floral lace with a sheer tulle skirt overlay — an heirloom piece for special days.",
  },
  {
    slug: "mocha-embroidered-eyelet-romper",
    name: "Mocha Floral-Embroidered Eyelet Romper",
    price: 799,
    ageRange: "3–12 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Mocha", hex: "#A8877A" }],
    sizes: ["3-6 Months", "6-9 Months", "9-12 Months"],
    image: n2Asset.url,
    isNew: true,
    fabric: "Cotton with floral embroidery",
    care: "Machine wash cold · Iron low",
    description: "Sleeveless mocha romper with white floral embroidery, eyelet-lace shoulder trim and snap-close bubble bottom.",
  },
  {
    slug: "red-corduroy-bow-romper",
    name: "Red Corduroy Bow-Embroidered Romper",
    price: 849,
    ageRange: "6–24 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Cherry Red", hex: "#A81E2B" }],
    sizes: ["6-12 Months", "12-18 Months", "18-24 Months"],
    image: n3Asset.url,
    isNew: true,
    bestSeller: true,
    fabric: "Soft baby corduroy",
    care: "Machine wash cold · Tumble dry low",
    description: "Festive red corduroy bubble romper with ruffled shoulders, button placket and tiny embroidered bows all over.",
  },
  {
    slug: "ditsy-floral-top-waffle-dungaree-set",
    name: "Ditsy Floral Top & Waffle Dungaree Romper Set",
    price: 899,
    ageRange: "3–12 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Cream Floral", hex: "#FFF0E8" }, { name: "Oat", hex: "#E3D5C0" }],
    sizes: ["3-6 Months", "6-9 Months", "9-12 Months"],
    image: n4Asset.url,
    isNew: true,
    fabric: "Cotton with waffle-knit dungaree",
    care: "Machine wash cold",
    description: "Ditsy floral ruffle-collar top paired with an oat waffle-knit ruffle dungaree romper with wooden buttons.",
  },
  {
    slug: "mint-embroidered-collar-romper-set",
    name: "Mint Embroidered Bow Romper with Collar Shirt",
    price: 949,
    ageRange: "6–18 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Mint", hex: "#BFE0DA" }, { name: "Ivory", hex: "#FFF8F0" }],
    sizes: ["6-9 Months", "9-12 Months", "12-18 Months"],
    image: n5Asset.url,
    isNew: true,
    fabric: "Embroidered cotton",
    care: "Hand wash cold",
    description: "Mint floral-embroidered bubble romper with side ribbon ties, layered over an ivory peter-pan collar puff-sleeve shirt.",
  },
  {
    slug: "gingham-shirt-waffle-dungaree-set",
    name: "Black Gingham Shirt & Waffle Dungaree Romper Set",
    price: 899,
    ageRange: "6–24 Months",
    category: "girls",
    gender: "Girls",
    colors: [{ name: "Black Gingham", hex: "#2B2B2B" }, { name: "Taupe", hex: "#A08D80" }],
    sizes: ["6-12 Months", "12-18 Months", "18-24 Months"],
    image: n6Asset.url,
    isNew: true,
    fabric: "Cotton flannel with waffle-knit",
    care: "Machine wash cold",
    description: "Black gingham button-down shirt paired with a taupe waffle-knit ruffle dungaree romper — a charming everyday set for little girls.",
  },
  {
    slug: "cream-satin-bow-knee-high-socks",
    name: "Cream Pointelle Knee-High Socks with Satin Bow",
    price: 249,
    ageRange: "0–3 Years",
    category: "footwear",
    gender: "Girls",
    colors: [{ name: "Cream", hex: "#F5E3C6" }],
    sizes: ["0-12 Months", "1-2 Years", "2-3 Years"],
    image: s1Asset.url,
    isNew: true,
    fabric: "Combed cotton pointelle knit",
    care: "Gentle machine wash cold · Dry flat",
    description: "Scallop-cuff pointelle knee-high socks in soft cream, finished with an oversized satin bow at the back.",
  },
  {
    slug: "blush-pointelle-bow-knee-high-socks",
    name: "Blush Pointelle Knee-High Socks with Grosgrain Bow",
    price: 249,
    ageRange: "0–3 Years",
    category: "footwear",
    gender: "Girls",
    colors: [{ name: "Blush Pink", hex: "#F6D3D0" }, { name: "White", hex: "#FFFFFF" }],
    sizes: ["0-12 Months", "1-2 Years", "2-3 Years"],
    image: s2Asset.url,
    isNew: true,
    fabric: "Breathable cotton pointelle knit",
    care: "Gentle machine wash cold · Dry flat",
    description: "Airy blush pointelle knee-highs with a scalloped white cuff and a neat ivory grosgrain bow.",
  },
  {
    slug: "white-fishnet-bow-knee-high-socks",
    name: "White Fishnet Knee-High Socks with Organza Bow",
    price: 299,
    ageRange: "6 Months–3 Years",
    category: "footwear",
    gender: "Girls",
    colors: [{ name: "White", hex: "#FFFFFF" }],
    sizes: ["6-12 Months", "1-2 Years", "2-3 Years"],
    image: s3Asset.url,
    isNew: true,
    bestSeller: true,
    fabric: "Stretch fishnet mesh",
    care: "Hand wash cold · Dry flat",
    description: "Dressy white fishnet knee-high socks topped with a big organza bow — perfect for parties and photoshoots.",
  },
  {
    slug: "ribbed-bow-knee-high-socks-set",
    name: "Ribbed Bow Knee-High Socks (Black, Ivory, Camel)",
    price: 279,
    ageRange: "0–3 Years",
    category: "footwear",
    gender: "Girls",
    colors: [{ name: "Black", hex: "#1C1C1C" }, { name: "Ivory", hex: "#FFF8F0" }, { name: "Camel", hex: "#D9A96C" }],
    sizes: ["0-12 Months", "1-2 Years", "2-3 Years"],
    image: s4Asset.url,
    isNew: true,
    fabric: "Ribbed cotton blend",
    care: "Gentle machine wash cold · Dry flat",
    description: "Soft ribbed knee-high socks with a satin side bow, available in black, ivory and camel.",
  },
  {
    slug: "fluffy-strawberry-hair-clips",
    name: "Fluffy Strawberry Hair Clip Set (Pair)",
    price: 199,
    ageRange: "1–6 Years",
    category: "accessories",
    gender: "Girls",
    colors: [{ name: "Ivory", hex: "#FFF6E8" }, { name: "Mocha", hex: "#8B6547" }],
    sizes: ["One Size"],
    image: s5Asset.url,
    isNew: true,
    fabric: "Faux fur with resin strawberry charm",
    care: "Spot clean only",
    description: "Cosy faux-fur snap clips finished with a sweet strawberry charm — sold as a pair in ivory or mocha.",
  },
  {
    slug: "lace-bow-nylon-headbands",
    name: "Embroidered Lace Bow Nylon Headband",
    price: 229,
    ageRange: "0–4 Years",
    category: "accessories",
    gender: "Girls",
    colors: [{ name: "White", hex: "#FFFFFF" }, { name: "Black", hex: "#1C1C1C" }],
    sizes: ["One Size"],
    image: s6Asset.url,
    isNew: true,
    fabric: "Floral embroidered lace on soft nylon band",
    care: "Hand wash cold · Dry flat",
    description: "Delicate floral lace bow on a super-soft nylon band that stays gentle on baby's head. Available in white and black.",
  },
];

export function getProduct(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}
